### ISSUE TITLE
hi, what happened to pigeonvideo

### ISSUE THREAD

**Issue by frappepancake** [LankyBox01/LankyBox01#4]
it said everything is archived. what happened?

**Comment by LankyBox01** [comment]
I cancelled it, However, i am working on [this](https://thenew90s.github.io/) now! Wanna join?

**Comment by frappepancake** [comment]
@LankyBox01 i found something bad
https://github.com/themagiclavalamp

**Comment by RiversideRocks** [comment]
its gone

**Comment by LankyBox01** [comment]
what do you mean it's gone? What's gone?

**Comment by RiversideRocks** [comment]
why?

**Comment by LankyBox01** [comment]
idk, too flashy background, i barely hit 30 views in 4 months, people just didn't like it.
